# Configuration for Packet Delivery Portal application

# Title of application
title: "Packet Delivery Portal"

# Client configuration
client:
  # Client ID
  id: "EU.EORI.NLPACKETDEL"
  # Client key (PEM private key)
  key: <pdc-private-key>
  # Client certificate (PEM certificate chain)
  crt: <pdc-certs>

# Configuration for external access
external:
  # Host (Hostname for external access)
  host: http://localhost

# OIDC configuration
oidc:
  # Path for OIDC redirect callback
  redirect_path: "/openid_connect1.0/return"
  # ACR values
  acr: "urn:http://eidas.europa.eu/LoA/NotNotified/high"

# Context Broker configuration
cb:
  # Endpoint of (API-Umbrella protected) NGSI-LD API
  endpoint: "https://localhost/ngsi-ld/v1"

# Configuration of express web server
express:
  # Port (Internal port of the express web server)
  port: 7000

# IDP configuration for login
idp:
  - name: "Happy Pets Inc."
    id: "EU.EORI.NLHAPPYPETS"
    url: "https://idp.happypets.com"
    authorize_endpoint: "https://idp.happypets.com/authorize"
    token_endpoint: "https://idp.happypets.com/token"
  - name: "No Cheaper Inc."
    id: "EU.EORI.NLNOCHEAPER"
    url: "https://idp.nocheaper.com"
    authorize_endpoint: "https://idp.nocheaper.com/authorize"
    token_endpoint: "https://idp.nocheaper.com/token"


