# Configuration for Packet Delivery Portal application

# Title of application
title: "Packet Delivery Portal"

# Client configuration
client:
  # Client ID
  id: "EU.EORI.NLPACKETDEL"
  # Client key (PEM private key)
  key: <pdc-private-key>
  # Client certificate (PEM certificate chain)
  crt: <pdc-certs>

# Configuration for external access
external:
  # Host (Hostname for external access)
  host: http://localhost

# OIDC configuration
oidc:
  # Path for OIDC redirect callback
  redirect_path: "/openid_connect1.0/return"
  # ACR values
  acr: "urn:http://eidas.europa.eu/LoA/NotNotified/high"

# Context Broker configuration
cb:
  # Endpoint of (PEP/PDP protected) NGSI-LD API (via OIDC flow)
  endpoint: "https://localhost/packetdelivery/ngsi-ld/v1"
  # Endpoint of (PEP/PDP protected) NGSI-LD API (via SIOP flow)
  endpoint_siop: "https://pdc-kong.i4trust-demo.fiware.dev/orion-vc/ngsi-ld/v1"

# Configuration of express web server
express:
  # Port (Internal port of the express web server)
  port: 7000

# Configuration for SIOP flow
siop:
  # SIOP flow enabled
  enabled: true
  # Redirect URI that the wallet will use to send the VC/VP
  redirect_uri: https://i4trust-demo-pdc-backend-vcbackend-i4trust-demo.apps.fiware.fiware.dev/verifier/api/v1/authenticationresponse
  # Base uri of the verifier
  verifier_uri: https://i4trust-demo-pdc-backend-vcbackend-i4trust-demo.apps.fiware.fiware.dev
  # DID of verifier
  did: "did:key:z6Mkk5iPrXg35fC4aq4yp3QadqVGKFhQL2b76fy6QKmSXJNT"
  # Type of credential that the Verifier will accept
  scope: "dsba.credentials.presentation.PacketDeliveryService"
  # Show separate Login button which shows the JWT access token only after login
  jwtOnlyEnabled: false

# IDP configuration for login
idp:
  - name: "Happy Pets Inc."
    id: "EU.EORI.NLHAPPYPETS"
    url: "https://idp.happypets.com"
    authorize_endpoint: "https://idp.happypets.com/authorize"
    token_endpoint: "https://idp.happypets.com/token"
  - name: "No Cheaper Inc."
    id: "EU.EORI.NLNOCHEAPER"
    url: "https://idp.nocheaper.com"
    authorize_endpoint: "https://idp.nocheaper.com/authorize"
    token_endpoint: "https://idp.nocheaper.com/token"


